@echo off
::---------------------------------------------------
:: Program : Automated Microsoft SQL Database Backup
:: Version : V1.0
:: Created by : Nestor B. Gramata Jr.
:: Date: May 2, 2017
:: Filename: DeleteTask@DBNAME.cmd
::---------------------------------------------------
:: Description:
::  Deletes a task
::  Used to easily undo the effects of CreateTask_DAYofWEEK_HHMMSS@DBNAME.cmd
::  Filename is used to extract variable information
::
:: Required Inputs/Arguments:
::  None
:: 
:: This is part of a group of files including:
::  1. MicSQL_Backup@DBNAME.cmd               (i.e. MicSQL_Backup@HR91.cmd)
::  2. CreateTask_DAYofWEEK_HHMMSS@DBNAME.cmd (i.e. CreateTask_TUE_000500@HR91.cmd)
::  3. DeleteTask@DBNAME.cmd                  (i.e. DeleteTask@HR91.cmd)
::  4. SendEmail.vbs
::  5. StoreSQLPass.cmd
::
:: IMPORTANT:
::	 Carefully change the filename
::   Create a separate empty folder where to place these 4 files! (i.e. E:\BACKUP\HR91\Automated)
::     - This is to prevent overwriting of files that may probably have the same name as that generated by the script
::   Run Script as Admin
::
:: Instructions:
::  1. Change DBNAME in the filename to appropriate Database Name (i.e. HR91)
::---------------------------------------------------

REM Info message
echo This deletes a task based on this script's filename after @

REM Get this scripts filename
set filename=%~n0
echo %FILENAME%

REM Parses the text after @ and uses it as the DBNAME
for /f "delims=@ tokens=2" %%x in ("%FILENAME%") do (set DBNAME=%%x)
echo %DBNAME%

REM Delete Task
schtasks /Delete /TN "MicSQL_Backup@%DBNAME%" /F

pause